# Generated by Django 4.2.29 on 2026-03-05 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_message_id', models.CharField(max_length=255, unique=True)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('message_text', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('whatsapp', 'WhatsApp Business')], max_length=20)),
                ('platform_user_id', models.CharField(max_length=255)),
                ('page_id', models.CharField(blank=True, help_text='Page/Business ID for Meta platforms', max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform', 'platform_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords/aliases for regex matching')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='MessageClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pricing', 'Pricing Query'), ('stock', 'Stock / Availability'), ('complaint', 'Complaint'), ('compliment', 'Compliment'), ('purchase_intent', 'Purchase Intent'), ('general', 'General Inquiry')], db_index=True, default='general', max_length=20)),
                ('confidence_keywords', models.TextField(blank=True, help_text='Keywords that triggered this classification')),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('matched_products', models.ManyToManyField(blank=True, related_name='classifications', to='analytics.product')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='analytics.directmessage')),
            ],
        ),
        migrations.AddField(
            model_name='directmessage',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytics.socialplatform'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CatalogUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='catalogs/')),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
